export default {
	ENV: process.env.NODE_ENV,
	DATABASE_URL: process.env.DATABASE_URL,
	DATABASE_POOL_IDLE: process.env.DATABASE_POOL_IDLE || 3000,
	DATABASE_POOL_MAX: process.env.DATABASE_POOL_MAX || 2,
	DATABASE_POOL_MIN: process.env.DATABASE_POOL_MIN || 0,
	DATABASE_POOL_ACQUIRE: process.env.DATABASE_POOL_ACQUIRE || 3000,
	BUCKET_NAME: process.env.BUCKET_NAME,
	IAM_USER_KEY: process.env.IAM_USER_KEY,
	IAM_USER_SECRET: process.env.IAM_USER_SECRET,
}
